# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy master branch

on:
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            Commit telah kami terima, saat ini code terbaru akan di Deploy secara automatis ke:
            - Domain: **https://console.krmpesan.com**

            Anda akan menerima notifikasi jika deploy telah selesai dilakukan, harap menunggu notifikasi selanjutnya.!

  build:
    runs-on: ubuntu-latest
    needs: check

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Load Dependencies Cache
        uses: c-hive/gha-yarn-cache@v1
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Load NextJS Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: Build NextJS Artifact
        run: yarn deploy
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Deploy to S3
        run: aws s3 sync . s3://console.krmpesan.com --acl public-read --size-only --delete
        working-directory: react-github-actions-build

  done:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            Deploy sukses, anda bisa mengecek preview website di:
            - Domain: **https://console.krmpesan.com**

            Jika ada kendala, jangan ragu untuk menghubungi team devops.!
